server:
  port: 8081

logging:
  file:
    name: logs/app.log

spring:
  application:
    name: Direkt

  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
