spring:
  config:
    import: classpath:secret.properties
  docker:
    compose:
      enabled: false
      file: docker/dev/docker-compose.yaml
      lifecycle-management: start_only

  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
    username: ${sb.stg.user}
    password: ${sb.stg.pw}

app:
  url:
    confirm: http://localhost:8081/api/v1/account/confirm

#logging:
#  level:
#    org.springframework.security: TRACE